//------------------------------------------------------------------------------
// File generated by Pixel Factory
// http://www.atnel.pl/pixel-factory.html
//------------------------------------------------------------------------------
#include <avr/io.h>
#include <avr/pgmspace.h>

const uint8_t ok[] PROGMEM = {
	0x38,0x8F,0x44,0x97,0x82,0xA7,0x82,0xC7,0x82,0xC7,0x82,0xA7,0x44,0x97,0x38,0x8F,
};

